# Generated by Django 5.2.14 on 2026-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Hewan')),
                ('species', models.CharField(choices=[('Cat', 'Kucing'), ('Dog', 'Anjing'), ('Other', 'Lainnya')], max_length=20, verbose_name='Jenis')),
                ('age', models.PositiveIntegerField(help_text='Umur dalam hitungan bulan', verbose_name='Umur (Bulan)')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Foto Hewan')),
                ('status', models.CharField(choices=[('Available', 'Tersedia'), ('Adopted', 'Sudah Diadopsi')], default='Available', max_length=20, verbose_name='Status Adopsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
