# Generated by Django 5.2.14 on 2026-05-31 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions', to=settings.AUTH_USER_MODEL, verbose_name='Pengadopsi'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Available', 'Tersedia'), ('Pending', 'Menunggu Persetujuan'), ('Adopted', 'Sudah Diadopsi')], default='Available', max_length=20, verbose_name='Status Adopsi'),
        ),
    ]
