# Generated by Django 5.2.14 on 2026-06-03 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_adopter_alter_pet_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Mengapa Anda ingin mengadopsi hewan ini?', verbose_name='Alasan Mengadopsi')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Pengalaman Memelihara Hewan')),
                ('status', models.CharField(choices=[('Pending', 'Menunggu Persetujuan'), ('Approved', 'Disetujui'), ('Rejected', 'Ditolak')], default='Pending', max_length=20, verbose_name='Status Pengajuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet', verbose_name='Hewan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pengadopsi')),
            ],
        ),
    ]
